/*
 * AccessDatabase.java ON 12/2/15 3:58 PM
 *   Copyright 2015 Tarakesh
 *   Copyright 2015 Arvind Mukund <arvind@MasterAwesome>
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the Free Software
 *   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 *   MA 02110-1301, USA.
 */

import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

class AccessDatabase extends javax.swing.JFrame {
    private String tablename = "";
    // --Commented out by Inspection (12/2/15 3:46 PM):Connection conn2 = null;
    private ResultSet rs = null;
    private Statement st = null;
    private Statement st2 = null;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;

    private AccessDatabase() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccessDatabase().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel jLabel1 = new JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        JButton jButton1 = new JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Select Database");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel());
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Find");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton1ActionPerformed(evt);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

        jButton2.setText("Next");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                107, Short.MAX_VALUE)
                                        .addComponent(jComboBox1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 102,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46))
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jButton1)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                196, Short.MAX_VALUE)
                                        .addComponent(jButton2)
                                        .addGap(38, 38, 38))
                );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(
                                                layout.createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(
                                                                jComboBox1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                48, Short.MAX_VALUE)
                                        .addGroup(
                                                layout.createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton1)
                                                        .addComponent(jButton2))
                                        .addContainerGap())
                );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(
            java.awt.event.ActionEvent evt)
            throws Exception {// GEN-FIRST:event_jButton1ActionPerformed
        DefaultComboBoxModel dcbm = null;
        dcbm = (DefaultComboBoxModel) jComboBox1.getModel();
        try {
            Class.forName("java.sql.DriverManager");
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
        Connection conn = DriverManager
                .getConnection("jdbc:mysql://localhost:3306/AI", "root", "root");
        st = conn.createStatement();
        st2 = conn.createStatement();

        String sql = "SHOW TABLES WHERE TABLES_IN_AI NOT LIKE 'CHOSENTABLE'";
        rs = st.executeQuery(sql);

        while (rs.next()) {
            dcbm.addElement(rs.getString("Tables_in_ai"));
        }

        String update = "INSERT INTO CHOSENTABLE VALUES ('" + tablename + "')";

        st2.executeUpdate(update);

        jButton2.setEnabled(true);

    }// GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(
            java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(
            java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        int i;
        i = jComboBox1.getSelectedIndex();
        tablename = (String) jComboBox1.getSelectedItem();
        System.out.println("TABLENAME =  " + tablename);
        // Use a non-default constructor here
        openTheQuestionsGUI(tablename);

        /*
         * Questions q = new Questions(); q.setVisible(true); q.setTitle(tablename);
         * this.setVisible(false); dispose();
         */

    }// GEN-LAST:event_jButton2ActionPerformed

    private void openTheQuestionsGUI(String tablename) {
        Questions questions = new Questions(tablename);
    }

}
